CONTRIBUTING.md, README.md
=> Created Contributing.md file

docker/hdfs/Dockerfile, docker/hdfs/files/build-hadoop.sh
Reduces the HDFS container image size from 1.02GB to 413MB (189MB compressed).
Closes #60
=> Gh 60 reduce hdfs container size

cd/deploy.sh
=> gh-65 Fix replaced newlines with \n characters in String

.gitignore, kubernetes/aws-eks-deployment.md, kubernetes/kind-deployment.md
- Explicitly declare nginx ingress controller version
- Update AWS ECR login command
=> gh-69 Updating Kind and AWS installation documentation:

cd/deploy.sh
=> gh-80 updated app version after generating charts

README.md, kubernetes/aws-eks-deployment.md, kubernetes/gaffer-road-traffic/docs/aws-eks-deployment.md, kubernetes/gaffer-road-traffic/docs/kind-deployment.md, kubernetes/gaffer/docs/aws-eks-deployment.md, kubernetes/gaffer/docs/kind-deployment.md, kubernetes/hdfs/docs/aws-eks-deployment.md, kubernetes/hdfs/docs/kind-deployment.md, kubernetes/kind-deployment.md
=> gh-84 Added Clarification of how to update accumulo passwords

kubernetes/gaffer-road-traffic/templates/data-loader-job.yaml, kubernetes/gaffer-road-traffic/templates/tests/integration/hdfs/hdfs-test.yaml, kubernetes/gaffer/templates/graph-upgrade-hook.yaml
=> gh-86 Removed workarounds

kubernetes/gaffer/templates/accumulo/config.yaml, kubernetes/gaffer/templates/api/ui-config.yaml, kubernetes/gaffer/templates/graph-config.yaml, kubernetes/gaffer/templates/schema.yaml, kubernetes/gaffer/templates/store-properties.yaml
=> gh-106 Add missing component labels to Gaffer resources

.github/workflows/release.yaml, README.md
=> gh-114 Made chart refer to itself for repositories

kubernetes/hdfs/templates/datanodes.yaml, kubernetes/hdfs/templates/namenode.yaml, kubernetes/hdfs/values.yaml
=> gh-122 Allow entire HDFS PVC template spec to be customised

kubernetes/gaffer/templates/accumulo/monitor/ingress.yaml, kubernetes/gaffer/templates/api/ingress.yaml, kubernetes/hdfs/templates/ingress.yaml, kubernetes/hdfs/values.yaml
=> gh-118 updated versions

.github/workflows/release.yaml
=> gh-130 fixed typo

kubernetes/gaffer/Chart.yaml
=> gh-139 - Updated Zookeeper URL

kubernetes/gaffer/templates/ingress.yaml, kubernetes/gaffer/values.yaml
=> optionally enable ingress on gaffer

README.md
adding the docker version that I currently use
- Resolve #50
=> Add known compatible docker versions

cd/install_dependencies.sh
=> dynamically get and order helm dependencies

docker/gaffer-jhub-options-server/templates/spark/notebook/executor-pod.yaml
=> Set the working directory for the executor Pods

.github/workflows/integration-test.yaml, cd/deploy_to_kind.sh, kubernetes/docs/kind-deployment.md
=> gh-222: Change kind usages to use kubernetes 1.21

.github/workflows/release.yaml
=> gh-225: Fix release action not seeing branch

.gitattributes
=> Cherry-pick gh-98 Stop git from auto converting line endings on clone (#242)

.github/workflows/integration-test.yaml, cd/deploy_to_kind.sh, docker/gaffer-jhub-options-server/Dockerfile, docker/gaffer-jhub-options-server/package.json, docker/gaffer-jhub-options-server/src/k8s-utils.js, docker/gaffer-jhub-options-server/src/spark-config-provisioner.js, docker/gaffer-jhub-options-server/src/spark-config-provisioner.test.js, kubernetes/docs/kind-deployment.md, kubernetes/gaffer-jhub/templates/hub/rbac.yaml, kubernetes/gaffer-jhub/templates/options-server/rbac.yaml
Fix for #221 by cherry-pick https://github.com/gchq/gaffer-docker/pull/247
- Resolve #248
=> Cherry-pick gh-221 Support multiple networking versions

.github/workflows/integration-test.yaml, cd/deploy_to_kind.sh, kubernetes/docs/kind-deployment.md
=> Set kubernetes version to 1.24.4 in kind CI

docker/accumulo/conf-2.0.1/log4j-monitor.properties, docker/accumulo/conf-2.0.1/log4j-service.properties
=> Gh-272: Accumulo 2 logger properties to use console

.github/workflows/create-alpha-release-branch.yaml, .github/workflows/create-hotfix-branch.yaml, .github/workflows/create-release-branch.yaml, .github/workflows/release.yaml
=> Consolidate develop release workflow with v2-alpha

.github/workflows/continuous-integration.yaml, .github/workflows/release.yaml
=> Gh 302: Cherry-pick CI (#299)

docker/gaffer-pyspark-notebook/Dockerfile, docker/gaffer-pyspark-notebook/README.md, docker/gaffer-pyspark-notebook/docker-compose.yaml
=> Gh-330: Update gafferpy references

.github/workflows/release.yaml, cd/build_core_images.sh
=> Gh-341: Fix Actions legacy images build

cd/publish_images.sh
=> Gh-345: Actions doesn't push Gremlin image

docker/gaffer-rest/README.md, docker/gaffer-rest/federated-example/compose.yaml, docker/gaffer-rest/federated-example/config/mergeFunctions.json, docker/gaffer-rest/federated-example/config/store.properties
=> Gh-368: Add Federated Store example

.github/workflows/release.yaml
Small fix for the release CI so it builds and uploads the correct version of the images.
=> Hotfix for the release CI
